# Generated by Django 4.2.7 on 2023-12-05 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('revise_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=50000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/%Y/%m/%d')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('revise_time', models.DateTimeField(auto_now=True)),
                ('content', models.CharField(max_length=1000)),
                ('Articles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='articles.articles')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
