# Generated by Django 4.2.7 on 2023-12-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_remove_report_content_report_report_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_article_pk',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
