# Generated by Django 4.2.7 on 2023-12-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_like_user_comment_like_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(choices=[('big three exercises ', '3대운동'), ('Lean Mass Up', '린매스업'), ('cardio', '유산'), ('bodybilding', '보디빌딩'), ('diet', '식단'), ('freedom', '자유')], default='', max_length=20),
        ),
    ]
