# Generated by Django 4.2.7 on 2023-12-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_report_report_article_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='content',
            new_name='my_content',
        ),
    ]
