# Generated by Django 4.2.7 on 2023-12-07 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='unlike_user',
            field=models.ManyToManyField(related_name='unlike_articles', to=settings.AUTH_USER_MODEL),
        ),
    ]
