# Generated by Django 4.2.7 on 2023-12-15 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_content_articles_my_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='my_content',
            new_name='content',
        ),
    ]
