# Generated by Django 4.2.7 on 2023-12-07 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_articles_unlike_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='category',
        ),
    ]
