# Generated by Django 4.2.7 on 2023-12-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_rename_my_content_articles_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
