# Generated by Django 4.2.7 on 2023-12-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_articles_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
