# Generated by Django 4.2.7 on 2023-12-10 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_comment_unlike_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='unlike_user',
        ),
    ]
