# Generated by Django 4.2.7 on 2023-12-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_remove_comment_unlike_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
