# Generated by Django 4.2.7 on 2023-12-11 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_articles_comment_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Articles',
            new_name='articles',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.comment'),
        ),
    ]
