# Generated by Django 4.2.7 on 2023-12-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_articles_popular_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='popular_article',
            field=models.CharField(blank=True, default=False, max_length=20, null=True),
        ),
    ]
