# Generated by Django 4.2.7 on 2023-12-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.CharField(blank=True, choices=[('big three exercises', '3대운동'), ('cycling', '싸이클'), ('bodyWeight_training', '맨몸운동'), ('bodybilding', '보디빌딩'), ('jogging', '조깅'), ('running', '러닝'), ('swimming', '수영'), ('WeightTraining', '웨이트트레이닝'), ('Yoga', '요가'), ('Pilates', '필라테스'), ('climbing', '클라이밍'), ('tennis', '테니스')], max_length=20, null=True, verbose_name='취미'),
        ),
    ]
