# Generated by Django 4.2.7 on 2024-01-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_nickname_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='hobby1',
            field=models.ManyToManyField(related_name='hobby1', to='accounts.hobby'),
        ),
        migrations.AddField(
            model_name='user',
            name='hobby2',
            field=models.ManyToManyField(related_name='hobby2', to='accounts.hobby'),
        ),
        migrations.AddField(
            model_name='user',
            name='hobby3',
            field=models.ManyToManyField(related_name='hobby3', to='accounts.hobby'),
        ),
    ]
