# Generated by Django 4.2.7 on 2024-01-12 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_hobby_user_hobby1_user_hobby2_user_hobby3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='slug',
        ),
    ]
