# Generated by Django 4.2.7 on 2023-12-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_hobbies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hobby1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hobby2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hobby3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
