# Generated by Django 4.2.7 on 2023-12-11 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_hobby1_user_hobby2_user_hobby3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobby1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobby2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobby3',
        ),
    ]
