# Generated by Django 4.2.7 on 2024-01-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_hobby_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobby1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobby2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobby3',
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(to='accounts.hobby'),
        ),
    ]
