# Generated by Django 4.2.7 on 2024-01-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_hobby1_remove_user_hobby2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hobbies',
            field=models.ManyToManyField(related_name='hobbies', to='accounts.hobby'),
        ),
    ]
