# Generated by Django 4.2.7 on 2023-12-21 06:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0008_alter_articles_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('goods_code', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('goods_name', models.CharField(max_length=1000)),
                ('goods_introduction', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('stock', models.IntegerField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.category')),
            ],
        ),
    ]
